[package]
name = "image_manipulator"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24.6"          # For image manipulation
rayon = "1.6"             # For parallel processing
thiserror = "1.0"         # For better error handling

